// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMUTD7QmWvhB_c3X87faNQric0sxo7mwM',
    appId: '1:750370149602:web:a2a1b84b6d65daa7fa3abb',
    messagingSenderId: '750370149602',
    projectId: 'firebase-auth-bloc2-02',
    authDomain: 'fir-auth-bloc2-02.firebaseapp.com',
    storageBucket: 'firebase-auth-bloc2-02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFlNjh58ZDzFizE8GafKWMO74nB8XiAO8',
    appId: '1:750370149602:android:ab2d1d642a210dc8fa3abb',
    messagingSenderId: '750370149602',
    projectId: 'firebase-auth-bloc2-02',
    storageBucket: 'firebase-auth-bloc2-02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-TxbVNDqDDCmLmrczBT_tsX94XeKwa_4',
    appId: '1:750370149602:ios:84d667e866b9798dfa3abb',
    messagingSenderId: '750370149602',
    projectId: 'firebase-auth-bloc2-02',
    storageBucket: 'firebase-auth-bloc2-02.appspot.com',
    iosClientId: '750370149602-3if9ffm3csv8gbsq3ulaghg66sd6rj4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthBloc',
  );
}
